TP2/TP2.Web/Controllers/PresupuestoController.cs
using iTextSharp.text;
using iTextSharp.text.pdf;
using OfficeOpenXml;
using OfficeOpenXml.Table;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using TP2.Entidades.EF;
using TP2.Negocio;

namespace TP2.Web.Controllers
{

    public class PresupuestoController : Controller
    {
           // public static  List<T_GUQ_PARTIDA> listaPartidas = new List<T_GUQ_PARTIDA>();
        public static List<Partida> listaPartidas = new List<Partida>();
            public  struct Partida
            {
                public int idPartida;
                public double monto;
                public string descripcion;
            } 

        //
        // GET: /Presupuesto/
        public ActionResult Index()
        {
            var listado = TGUQPresupuesto.ListarTodos();
            return View(listado);
        }

        public ActionResult Create()
        {
            listaPartidas.Clear();
            var partidaList = TGUQPartida.ListarTodos();
            ViewBag.PartidaList = partidaList;

            var areaList = TGUQArea.ListarTodos();
            ViewBag.AreaList = areaList;

            return View();
        }

        [HttpPost]
        public string Create(T_GUQ_PRESUPUESTO presupuesto)
        {
            string mensaje = "Error al grabar los datos";

            if (DateTime.Now.Year != presupuesto.anio)
            {
                mensaje = "Error : No puede grabar presupuesto en ese año: " + presupuesto.anio;
                return mensaje;
            }

            if (listaPartidas.Count() == 0)
            {
                mensaje = "Error : No puede grabar presupuesto sin partida";
                return mensaje;
            }

          
            foreach (var item in TGUQPresupuesto.ListarTodos())
            {
                if(item.anio == presupuesto.anio && item.idArea == presupuesto.idArea){
                    mensaje = "Error : Ya existe presupuesto para este año y esa área";
                    return mensaje;
                }
            }

            
            List<T_GUQ_PARTIDA> lisPartidas = new List<T_GUQ_PARTIDA>();
            T_GUQ_PARTIDA oPartida ;
            List<double> listaMontos = new List<double>();
            double montoTotal = 0;
            for (int i = 0; i < listaPartidas.Count(); i++)
            {
                montoTotal = montoTotal + listaPartidas[i].monto;
                oPartida = new T_GUQ_PARTIDA();
                oPartida.idPartida = listaPartidas[i].idPartida;
                oPartida.dscPartida = listaPartidas[i].descripcion;
                lisPartidas.Add(oPartida);
                listaMontos.Add(listaPartidas[i].monto);
            }


            bool exito = TGUQPresupuesto.Crear(presupuesto, lisPartidas, listaMontos);
            if (exito)
                mensaje = "Los datos se grabaron con exito";
            return mensaje;
        }

        public ActionResult Edit(int id)
        {

            var presupuesto = TGUQPresupuesto.Obtener(id);

            var partidaList = TGUQPartida.ListarTodos();
            ViewBag.PartidaList = new SelectList(partidaList, "idPartida", "dscPartida");

            var areaList = TGUQArea.ListarTodos();
            ViewBag.AreaList = new SelectList(areaList, "idArea", "descripcion", presupuesto.idArea);
            
            return View(presupuesto);
            //return Json(listaPartidas, JsonRequestBehavior.AllowGet);  
        }

         [HttpPost]
        public string Edit(T_GUQ_PRESUPUESTO presupuesto)
        {
            string mensaje = "Error al grabar los datos";

            if (listaPartidas.Count() == 0)
            {
                mensaje = "Error : No puede grabar presupuesto sin partida";
                return mensaje;
            }

            T_GUQ_PRESUPUESTO oPresupuesto = TGUQPresupuesto.Obtener(presupuesto.idPresupuesto);
            List<T_GUQ_PARTIDA> lisPartidas = new List<T_GUQ_PARTIDA>();
            T_GUQ_PARTIDA oPartida;
            List<double> listaMontos = new List<double>();
            double montoTotal = 0;

            for (int i = 0; i < listaPartidas.Count(); i++)
            {
                montoTotal = montoTotal + listaPartidas[i].monto;
                oPartida = new T_GUQ_PARTIDA();
                oPartida.idPartida = listaPartidas[i].idPartida;
                oPartida.dscPartida = listaPartidas[i].descripcion;
                lisPartidas.Add(oPartida);
                listaMontos.Add(listaPartidas[i].monto);
            }

            bool exito = TGUQPresupuesto.Editar(oPresupuesto, lisPartidas, listaMontos);
      
            if (exito)
                mensaje = "Los datos se grabaron con exito";
            return mensaje;
        }


        [HttpPost]
        public ActionResult ListarPartidas(int IdPresupuesto)
        {

            listaPartidas.Clear();
            var presupuesto = TGUQPresupuesto.Obtener(IdPresupuesto);

            if (presupuesto.anio != DateTime.Now.Year)
            {
                return Json("1", JsonRequestBehavior.AllowGet);
            }

            if (presupuesto.estado == "Generado")
            {
                Partida partida;

                foreach (var item in presupuesto.T_GUQ_PRESUPUESTO_PARTIDA)
                {
                    var oPartida = TGUQPartida.Obtener(item.idPartida);
                    partida = new Partida();
                    partida.idPartida = item.idPartida;
                    partida.monto = item.montoPartida;
                    partida.descripcion = oPartida.dscPartida;
                    listaPartidas.Add(partida);
                }

                return Json(listaPartidas, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("2", JsonRequestBehavior.AllowGet);
            }
          
        }


        [HttpPost]
        public ActionResult AgregarPartida(T_GUQ_PRESUPUESTO presupuesto, int partida)
        {
            foreach (var item in listaPartidas)
            {
                if (item.idPartida == partida)
                {
                  
                    return Json("Error", JsonRequestBehavior.AllowGet); 
                }
            }

            double monto = presupuesto.monto;
            var Partida = TGUQPartida.Obtener(partida);
            Partida oPartida = new Partida();
            oPartida.monto = Math.Round(monto,2);
            oPartida.idPartida = partida;
            oPartida.descripcion = Partida.dscPartida;
            listaPartidas.Add(oPartida);
            return Json(listaPartidas, JsonRequestBehavior.AllowGet);  
        }

        
        public ActionResult EditarPartida(int idPartida)
        {
            for (int i = 0; i < listaPartidas.Count(); i++)
            {
                if (listaPartidas[i].idPartida == idPartida)
                {
                    return Json(listaPartidas[i], JsonRequestBehavior.AllowGet);
                }
            }

            return Json("", JsonRequestBehavior.AllowGet);
           
        }

        [HttpPost]
        public ActionResult EditarPartida(int idPartida, double monto)
        {
            for (int i = 0; i < listaPartidas.Count(); i++)
            {
                if (listaPartidas[i].idPartida == idPartida)
                { 
                    var Partida = TGUQPartida.Obtener(idPartida);
                    Partida oPartida = new Partida();
                    oPartida.monto = monto;
                    oPartida.idPartida = idPartida;
                    oPartida.descripcion = Partida.dscPartida;
                    listaPartidas[i]= oPartida;
                }
            }
         

            return Json(listaPartidas, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public ActionResult EliminarPartida(int idPartida)
        {
            listaPartidas.RemoveAll(x => x.idPartida == idPartida);
            return Json(listaPartidas, JsonRequestBehavior.AllowGet);

        }

        public ActionResult ExportToExcel(int id)
        {
            var presupuesto = TGUQPresupuesto.Obtener(id);
           
           
            using(var excelPackage = new ExcelPackage()){
                 //Propiedades del archivo
                 excelPackage.Workbook.Properties.Author = "Yovanny Zeballos ";
                 excelPackage.Workbook.Properties.Title = " Exportación de Presupuestos";

                 //Propiedades Hoja de excel
                 var sheet = excelPackage.Workbook.Worksheets.Add("Presupuestos");
                 sheet.Name = "Presupuestos";

                //Empezamos a escribir sobre ella.
                var rowindex=1 ;

                //Hago un Merge de primeras 4 columnas para poner el titulo.
               sheet.Cells[1, 1].Value = "PRESUPUESTO : " + presupuesto.anio +" AREA: "+ presupuesto.T_GUQ_AREA.descripcion;
               sheet.Cells[1, 1, 1, 4].Merge = true;


                //Pongo los encabezados del excel
                var col = 1;
                sheet.Cells[3, col++].Value = "Año";
                sheet.Cells[3,col++].Value= "Area";
                sheet.Cells[3, col++].Value = "Partida";
                sheet.Cells[3, col++].Value = "Monto";
                rowindex = 4;

                var montoTotal = 0.0;
                //Recorro los recibos y los ponemos en el Excel
                foreach (var item in presupuesto.T_GUQ_PRESUPUESTO_PARTIDA)
                {
                    var oPartida = TGUQPartida.Obtener(item.idPartida);
                    col = 1;
                    sheet.Cells[rowindex, col++].Value = item.T_GUQ_PRESUPUESTO.anio;
                    sheet.Cells[rowindex, col++].Value = item.T_GUQ_PRESUPUESTO.T_GUQ_AREA.descripcion;
                    sheet.Cells[rowindex, col++].Value = item.T_GUQ_PARTIDA.dscPartida;

TP2/TP2.Web/Controllers/ReservaController.cs
using System;
using System.Web.Mvc;
using System.Linq;
using TP2.Entidades.EF;
using TP2.Negocio;

namespace TP2.Web.Controllers
{
    public class ReservaController : Controller
    {
        // GET: Reserva

        public ActionResult Index()
        {
            var listado = TGUQReservaSalaOperacion.ListarTodos();
            return View(listado);
        }

        public ActionResult Create()
        {
            var tipoOperacionList = TGUQTipoOperacion.ListarTodos();
            ViewBag.TipoOperacionList = tipoOperacionList;

            var pacienteList = TGDAPaciente.ListarTodos();
            ViewBag.PacienteList = pacienteList;

            return View();
        }

        public ActionResult MedicoPartial(int tipo, string fecha, string hora)
        {
            hora = hora.Substring(0, 2);
            var nuevaHora = int.Parse(hora);
            var nuevaFecha = DateTime.Parse(fecha);

            var empleadoList = TGUQReservaSalaOperacion.ListarMedicos(tipo, nuevaFecha, nuevaHora);
            return PartialView("_ReservaMedico", empleadoList);
        }

        public ActionResult HorarioPartial(string fecha, int inmueble, int tipo)
        {
            var salaList = TGUQReservaSalaOperacion.ListarHorarios(fecha, inmueble, tipo);
            return PartialView("_ReservaSala", salaList);
        }

        public ActionResult PacientePartial(int tipo, string fecha, string hora)
        {
            hora = hora.Substring(0, 2);
            var nuevaHora = int.Parse(hora);
            var nuevaFecha = DateTime.Parse(fecha);
            var pacienteList = TGUQReservaSalaOperacion.ListarPacientes(tipo, nuevaFecha, nuevaHora);

            return PartialView("_Paciente", pacienteList);
        }

        public ActionResult ObtenerSalas(int tipo)
        {
            var lista = TGGInmueble.ListarDisponibles(tipo).Select(p => new { Id = p.idInmueble, Nombre = p.dscTipoInmueble }).ToList();
            return Json(lista, JsonRequestBehavior.AllowGet);

        }

        public int ObtenerDuracion(int tipo)
        {
            int duracion = 0;
            var tipoOperacion = TGUQTipoOperacion.Obtener(tipo);
            if (tipoOperacion != null && tipoOperacion.duracion.HasValue)
                duracion = tipoOperacion.duracion.Value;
            return duracion;

        }

        [HttpPost]
        public string Create(T_GUQ_RESERVA_SALA_OPERACIÓN reserva, string horaInicio)
        {
            horaInicio = horaInicio.Substring(0, 2);
            var nuevaHora = int.Parse(horaInicio);
            reserva.fechaInicio = reserva.fechaInicio.AddHours(nuevaHora);
            reserva.fechaFin = reserva.fechaInicio.AddHours(reserva.duración);

            string mensaje = "Error al grabar los datos";
            bool exito = TGUQReservaSalaOperacion.Crear(reserva);
            if (exito)
                mensaje = "Los datos se grabaron con exito";
            return mensaje;
        }
    }
}

TP2/TP2.Web/Views/Shared/ShortDateTime.cshtml
@model System.DateTime

@Model.ToShortDateString()

TP2/TP2.Web/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Layout</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/Script/modernizr")
</head>
<body>
    <div class="container">
        <div class="col-md-3">
            @Html.Partial("_Sidebar")
        </div>
        <div class="col-md-9">
            <div class="text-left">
                <img src="~/Images/logocrp.gif" style="width:150px;" />
            </div>
            @RenderBody()
        </div>
    </div>
    @Scripts.Render("~/Script/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

TP2/TP2.Web/Views/Shared/_Paciente.cshtml
@model  IEnumerable<TP2.Entidades.EF.T_GDA_PACIENTE>
<table class="table table-condensed table-striped table-bordered" id="tblPaciente">
    <tr>
        <td>Nombre</td>
        <td>Direcci&oacute;n</td>
        <td></td>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.nomPaciente</td>
            <td>@item.numDNI</td>
            <td>
                <input type="radio" value="@item.idPaciente" id="optPaciente" name="rbPaciente">
            </td>
        </tr>
    }
</table>

TP2/TP2.Web/Views/Shared/_ReservaMedico.cshtml
@model  IEnumerable<TP2.Entidades.EF.T_GG_EMPLEADO>
<form>
    @foreach (var item in Model)
    {
        <div class="radio col-md-12">
            <label><input type="radio" name="rbMedico" value="@item.idEmpleado">@item.nomEmpleado</label>
        </div>
    }
</form>

TP2/TP2.Web/Views/Shared/_ReservaSala.cshtml
@model  IEnumerable<string>
<form>
    @foreach (var item in Model)
    {
        <label class="radio-inline">
            <input type="radio" value="@item" id="rbHorario" name="rbHorario" onchange="obtenerMedicos()">@item
        </label>
    }
</form>

TP2/TP2.Web/Views/Shared/_Sidebar.cshtml
<nav class="navbar navbar-default sidebar" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Inicio<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
                <li><a href="#">Solicitud de sala<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-tags"></span></a></li>
                <li><a href="@Url.Action("Index", "Reserva")">Horario de operaci&oacute;n<span style=" font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-th-list"></span></a></li>
                <li><a href="@Url.Action("Index", "Presupuesto")">Presupuesto Anual<span style=" font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-th-list"></span></a></li>
            </ul>
        </div>
    </div>
</nav>